import Head from "next/head";
import Image from "next/image";
import tw from "twin.macro";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hello>hello</Hello>
    </div>
  );
}

const Hello = tw.div`
text-3xl 
font-mono
text-red-500
`;
